### ISSUE TITLE
Please help me build the library

### ISSUE THREAD

**Issue by dacdave** [RusticiSoftware/TinCanJava#35]
I am unfamiliar with Maven. I had this building on my previous laptop but purchased a new one. I cannot get it to build on the new machine, Windows 8.1 - same as the previous machine.

The first goal that creates errors is test-compile. Therefore the command:

>mvn test-compile

generates the following errors:

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[24,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[25,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[26,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[24,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[25,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[26,44] package com.rusticisoftware.tincan.documents does not exist
[ERROR] /C:/Users/Dave/Workspaces/xAPI/TinCanJava/src/test/java/com/rusticisoftware/tincan/RemoteLRSTest.java:[379,9] cannot find symbol
  symbol:   class StateDocument
  location: class com.rusticisoftware.tincan.RemoteLRSTest
...

What follows next is a long list of the Java classes that cannot be found by module RemoteLRSTest.java because it cannot find the package com.rusticisoftware.tincan.documents.

Any help will be greatly appreciated.

Dave Smith

**Comment by dacdave** [comment]
I got this working.

If anyone else is interested, I opened the project in Eclipse and converted the Eclipse project to a Maven project. This actually did not complete successfully within Eclipse; however, after that I am able to build successfully using the command line mvn command.
